// Build pipeline for fhmic/home
//
// Edit your real pages in src/. Run `npm run build` before every commit/push.
// This produces docs/ — a concealed, obfuscated, hashed-filename version of
// the site that GitHub Pages actually serves (Pages source: "main /docs").
//
// WHY THE BODY IS EMPTY IN THE SHIPPED HTML
// -------------------------------------------
// A plain static HTML page always has to show its own markup in
// "view source", because the browser needs that markup to render the page.
// An SPA (like fm-portal, built with Vite/React) looks nearly empty in
// "view source" instead, because its entire body is generated by JavaScript
// at runtime into a single empty container (<div id="root">).
//
// This build reproduces that same effect for plain HTML pages: each page's
// <body> markup is captured as a string, folded into that page's obfuscated
// JS bundle (so it's hex/base64-encoded like everything else the obfuscator
// touches), and injected into an empty container via .innerHTML at runtime.
// The shipped HTML shell ends up looking like fm-portal's: <head> + a single
// empty <div> + one <script src>.
//
// This does NOT change behavior: inline onclick="fn()" style attributes
// still work identically whether the HTML containing them was written by
// hand or inserted via innerHTML — the browser attaches those handlers the
// same way either way. Global function names referenced by such attributes
// are still auto-detected and protected from renaming (reservedNames).

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const JavaScriptObfuscator = require('javascript-obfuscator');
const CleanCSS = require('clean-css');

const SRC_DIR = path.join(__dirname, 'src');
const OUT_DIR = path.join(__dirname, 'docs');
const ASSETS_DIR = path.join(OUT_DIR, 'assets');
const ROOT_ID = '__shell_root__';

const PAGES = [
  { name: 'index', dir: '' },
  { name: 'capmax', dir: 'capmax' },
  { name: 'gmi', dir: 'gmi' },
  { name: 'job', dir: 'job' },
  { name: 'portal', dir: 'portal' },
  { name: 'receivables', dir: 'receivables' },
  { name: 'recon', dir: 'recon' },
  { name: 'treasury', dir: 'treasury' },
];

const PASSTHROUGH_FILES = ['img.jpg', 'pix.jpg'];

const JS_KEYWORDS = new Set([
  'if', 'else', 'return', 'this', 'void', 'new', 'typeof', 'window',
  'document', 'true', 'false', 'null', 'undefined', 'function', 'var',
  'let', 'const', 'for', 'while', 'switch', 'case', 'break', 'continue',
  'delete', 'in', 'of', 'instanceof', 'do', 'try', 'catch', 'finally',
  'throw', 'event', 'confirm', 'alert',
]);

function hashOf(content) {
  return crypto.createHash('md5').update(content).digest('hex').slice(0, 8);
}

// Scan the ORIGINAL (pre-obfuscation) HTML for every on*="..." / on*='...'
// attribute and href="javascript:..." call, and return the set of global
// function names that must survive obfuscation untouched.
function collectReservedNames(html) {
  const names = new Set();
  const attrPatterns = [
    /\son\w+\s*=\s*"([^"]*)"/gi,
    /\son\w+\s*=\s*'([^']*)'/gi,
    /href\s*=\s*"javascript:([^"]*)"/gi,
    /href\s*=\s*'javascript:([^']*)'/gi,
  ];
  for (const re of attrPatterns) {
    let m;
    while ((m = re.exec(html)) !== null) {
      const body = m[1];
      for (const stmt of body.split(';')) {
        const call = stmt.trim().replace(/^return\s+/, '');
        const idMatch = call.match(/^([a-zA-Z_$][a-zA-Z0-9_$]*)\s*\(/);
        if (idMatch && !JS_KEYWORDS.has(idMatch[1])) {
          names.add(idMatch[1]);
        }
      }
    }
  }
  return Array.from(names);
}

function stripHtmlComments(html) {
  return html.replace(/<!--[\s\S]*?-->/g, '');
}

function obfuscateJs(code, reservedNames) {
  const result = JavaScriptObfuscator.obfuscate(code, {
    compact: true,
    controlFlowFlattening: true,
    controlFlowFlatteningThreshold: 0.75,
    deadCodeInjection: true,
    deadCodeInjectionThreshold: 0.4,
    stringArray: true,
    stringArrayEncoding: ['base64'],
    stringArrayThreshold: 0.75,
    identifierNamesGenerator: 'hexadecimal',
    renameGlobals: true,
    reservedNames: reservedNames.map((n) => `^${n}$`),
    selfDefending: false,
    debugProtection: false,
    disableConsoleOutput: false,
    target: 'browser',
  });
  return result.getObfuscatedCode();
}

function processPage(page) {
  const srcPath = path.join(SRC_DIR, page.dir, 'index.html');
  let html = fs.readFileSync(srcPath, 'utf8');

  const reservedNames = collectReservedNames(html);

  // Root page lives at docs/index.html (one level above docs/assets/), so
  // "./assets/..." is correct there. Every subpage (e.g. docs/portal/) is
  // one level DEEPER than docs/assets/, so it needs "../assets/...".
  const depth = page.dir ? page.dir.split('/').filter(Boolean).length : 0;
  const assetsPrefix = depth === 0 ? './assets/' : '../'.repeat(depth) + 'assets/';

  // 1. Extract & minify inline <style>...</style> blocks (these live in
  //    <head> on every page here, so this is safe to do before touching body)
  const styleRe = /<style>([\s\S]*?)<\/style>/g;
  let styleIdx = 0;
  const styleReplacements = [];
  html = html.replace(styleRe, (match, css) => {
    styleIdx++;
    const minified = new CleanCSS({ level: 2 }).minify(css).styles;
    const hash = hashOf(minified);
    const fname = `${page.name}-style${styleIdx > 1 ? styleIdx : ''}-${hash}.css`;
    styleReplacements.push({ fname, content: minified });
    return `<link rel="stylesheet" href="${assetsPrefix}${fname}">`;
  });

  // 2. Split into head / body. Everything in <head> (meta, the stylesheet
  //    link just added, and any CDN <script src="..."> library tags) stays
  //    exactly as-is and untouched — those need to stay as real elements so
  //    the browser actually loads/executes them.
  const bodyMatch = html.match(/<body([^>]*)>([\s\S]*)<\/body>/);
  if (!bodyMatch) {
    throw new Error(`${page.name}: could not find a <body>...</body> to process`);
  }
  const [fullBodyMatch, bodyAttrs, bodyInnerRaw] = bodyMatch;
  const headPart = html.slice(0, bodyMatch.index);
  const afterBodyPart = html.slice(bodyMatch.index + fullBodyMatch.length);

  // 3. Pull every inline <script>...</script> (no src=) OUT of the body
  //    entirely, in document order, leaving pure visible markup behind.
  const behaviorScripts = [];
  const bodyMarkupOnly = bodyInnerRaw.replace(/<script>([\s\S]*?)<\/script>/g, (m, js) => {
    behaviorScripts.push(js);
    return '';
  });

  // 4. The remaining markup (nav, sections, forms, buttons — everything a
  //    visitor sees) becomes a plain string, safely escaped as JSON so it's
  //    valid JS regardless of quotes/newlines/unicode inside it. This is a
  //    STANDALONE .js file, not an inline <script> in the HTML, so there's
  //    no "</script>"-inside-a-string HTML-parsing hazard to worry about.
  const markupForInjection = stripHtmlComments(bodyMarkupOnly);
  const injectionStatement =
    `document.getElementById(${JSON.stringify(ROOT_ID)}).innerHTML=` +
    `${JSON.stringify(markupForInjection)};`;

  // 5. Combine: inject markup first, then run the page's original behavior
  //    scripts in their original relative order — same effective order as
  //    before, since those scripts always ran after their preceding markup
  //    had already been parsed.
  const combinedSource = [injectionStatement, ...behaviorScripts].join('\n');
  const obfuscated = obfuscateJs(combinedSource, reservedNames);
  const hash = hashOf(obfuscated);
  const appFname = `${page.name}-app-${hash}.js`;
  fs.mkdirSync(ASSETS_DIR, { recursive: true });
  fs.writeFileSync(path.join(ASSETS_DIR, appFname), obfuscated, 'utf8');

  // 6. Rebuild the shell: same <head>, a body with just the empty container
  //    + one script tag, same trailing content (there normally isn't any
  //    after </body> in these files, but preserve it just in case).
  const newBody =
    `<body${bodyAttrs}>\n<div id="${ROOT_ID}"></div>\n` +
    `<script src="${assetsPrefix}${appFname}"></script>\n</body>`;
  let finalHtml = stripHtmlComments(headPart) + newBody + afterBodyPart;

  const outHtmlDir = path.join(OUT_DIR, page.dir);
  fs.mkdirSync(outHtmlDir, { recursive: true });
  fs.writeFileSync(path.join(outHtmlDir, 'index.html'), finalHtml, 'utf8');

  for (const { fname, content } of styleReplacements) {
    fs.writeFileSync(path.join(ASSETS_DIR, fname), content, 'utf8');
  }

  console.log(
    `✔ ${page.name}: ${styleReplacements.length} style file(s), 1 app bundle ` +
    `(${behaviorScripts.length} behavior script(s) folded in), ${reservedNames.length} reserved name(s)`
  );
}

function main() {
  fs.rmSync(OUT_DIR, { recursive: true, force: true });
  for (const page of PAGES) {
    processPage(page);
  }
  for (const f of PASSTHROUGH_FILES) {
    const src = path.join(SRC_DIR, f);
    if (fs.existsSync(src)) {
      fs.copyFileSync(src, path.join(OUT_DIR, f));
    }
  }
  console.log('\nBuild complete →', OUT_DIR);
}

main();
